name        = "ncurses"
version     = "6.5"
description = "Biblioteca de manipulação de terminal em modo texto"
depends     = []
source      = "https://invisible-mirror.net/archives/ncurses/ncurses-6.5.tar.gz"
# sha256 = "preencha com: sha256sum ncurses-6.5.tar.gz"
build_system = "autotools"
configure_args = [
    "--mandir=/usr/share/man",
    "--with-shared",
    "--without-debug",
    "--without-normal",
    "--enable-widec",
]
# ldconfig após instalar para as libs shared serem encontradas
post_install = ["ldconfig"]
